In [ ]:
L=[]
for i in range (2000,3201):
  if i % 7 == 0 and i % 5 != 0:
    L.append(i)
L

[2002,
 2009,
 2016,
 2023,
 2037,
 2044,
 2051,
 2058,
 2072,
 2079,
 2086,
 2093,
 2107,
 2114,
 2121,
 2128,
 2142,
 2149,
 2156,
 2163,
 2177,
 2184,
 2191,
 2198,
 2212,
 2219,
 2226,
 2233,
 2247,
 2254,
 2261,
 2268,
 2282,
 2289,
 2296,
 2303,
 2317,
 2324,
 2331,
 2338,
 2352,
 2359,
 2366,
 2373,
 2387,
 2394,
 2401,
 2408,
 2422,
 2429,
 2436,
 2443,
 2457,
 2464,
 2471,
 2478,
 2492,
 2499,
 2506,
 2513,
 2527,
 2534,
 2541,
 2548,
 2562,
 2569,
 2576,
 2583,
 2597,
 2604,
 2611,
 2618,
 2632,
 2639,
 2646,
 2653,
 2667,
 2674,
 2681,
 2688,
 2702,
 2709,
 2716,
 2723,
 2737,
 2744,
 2751,
 2758,
 2772,
 2779,
 2786,
 2793,
 2807,
 2814,
 2821,
 2828,
 2842,
 2849,
 2856,
 2863,
 2877,
 2884,
 2891,
 2898,
 2912,
 2919,
 2926,
 2933,
 2947,
 2954,
 2961,
 2968,
 2982,
 2989,
 2996,
 3003,
 3017,
 3024,
 3031,
 3038,
 3052,
 3059,
 3066,
 3073,
 3087,
 3094,
 3101,
 3108,
 3122,
 3129,
 3136,
 3143,
 3157,
 3164,
 3171,
 3178,
 3192,
 3199]

In [ ]:
def question_2 (n):
  f=1
  for i in range (1,n+1):
    f=f*i
  print(f)

In [ ]:
question_2(3)

6


In [ ]:
question_2(5)

120


In [ ]:
import math
print(math.factorial(5))

120


In [ ]:
d={}
n=int(input("donner la longeur"))
def q3 (n):
  for i in range (1,n+1):
    d[i]=i*i
  print(d)

q3(n)

donner la longeur8
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}


In [ ]:
q3(8)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}


In [ ]:
n=int(input("donner n"))
st=input("donner str")
st1=""
for i in range (0,n):
  st1=st[i]+st1
for i in range (n+1,len(st)):
  st1=st[i]+st1
print(st1)


donner n5
donner strazertyui
iutreza


In [ ]:
import numpy as np

matrice1=np.random.randint(1,10,(2,2))
matrice2=np.random.randint(1,10,(2,2))
print(np.cov(matrice1,matrice2))

[[ 2.  6.  4.  0.]
 [ 6. 18. 12.  0.]
 [ 4. 12.  8.  0.]
 [ 0.  0.  0.  0.]]


In [ ]:
dir(matrice)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [ ]:
L=list(input("donner la liste"))

donner la liste1,10,5,5


In [ ]:
print(L)

['1', ',', '1', '0', ',', '5', ',', '5']


In [ ]:
L=list(input("donner la liste"))


donner la liste1 10 52 64 2 


In [ ]:
PRINT(L)

NameError: ignored

In [ ]:
print(L)

['1', ' ', '1', '0', ' ', '5', '2', ' ', '6', '4', ' ', '2', ' ']


In [ ]:
import numpy as np
n=int(input("donner la longeur"))
L1=[]
for i in range(0,(n-1)):
  e=int(input("entrer l'element"))
  L1.append(e)
  L1[i]=np.sqrt(2*50*L[i]/30)
print(L)


donner la longeur5
entrer l'element1


TypeError: ignored

In [ ]:
5